name: Auto-rebase dev on main changes

on:
  push:
    branches:
      - main

jobs:
  rebase:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "UjjwalAgr14"
          git config --global user.email "ujjwal@recruitcrm.io"
          git checkout dev

      - name: Pull changes from main
        run: git pull origin main

      - name: Push changes to dev
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          git remote set-url origin https://github.com/UjjwalAgr14/rebase-automation-test.git
          git push origin dev
