name: Auto-rebase dev on main changes

on:
  push:
    branches:
      - main

jobs:
  rebase:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name UjjwalAgr14
          git config --global user.email ujjwal@recruitcrm.io
          git checkout -b dev

      - name: Pull changes from main
        run: git pull origin main

      - name: Enable rerere
        run: git config --global rerere.enabled true

      - name: Automatic rebase with conflict resolution
        run: |
          while git rebase --continue; do :; done
          if [ $? -eq 0 ]; then
            git push origin dev
          else
            echo "Automatic rebase with conflict resolution failed."
            exit 1
          fi
