name: Automated Rebase

on:
  push:
    branches:
      - main

jobs:
  rebase:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "UjjwalAgr14"
          git config --global user.email "ujjwal@recruitcrm.io"
          git remote set-url origin https://github.com/UjjwalAgr14/rebase-automation-test.git
          git fetch origin dev
          git checkout dev

      - name: Enable rerere
        run: git config --global rerere.enabled true

      - name: Pull changes from main and rebase
        run: git pull origin main --rebase --autosquash

      - name: Automatic rebase with conflict resolution
        run: |
          while git rebase --continue; do :; done
          if [ $? -eq 0 ]; then
            git push origin HEAD:dev --force-with-lease
          else
            echo "Automatic rebase with conflict resolution failed."
            exit 1
          fi
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
