name: Automated Merge

on:
  push:
    branches:
      - main

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "UjjwalAgr14"
          git config --global user.email "ujjwal@recruitcrm.io"
          git remote set-url origin https://github.com/UjjwalAgr14/rebase-automation-test.git
          git fetch origin dev
          git checkout dev

      - name: Set pull strategy to merge
        run: git config pull.rebase false

      - name: Create an initial commit in dev branch
        run: git commit --allow-empty -m "Initial commit"

      - name: Merge changes from main into dev
        run: git merge origin/main --allow-unrelated-histories

      - name: Automatic merge with conflict resolution
        run: |
          while git diff --name-only --diff-filter=U | grep -q .; do
            echo "Conflict found, resolving conflicts..."
            git checkout --theirs .
            git add .
          done
          git commit -m "Merge conflict resolution"
          git push origin HEAD:dev
