name: Automated Rebase

on:
  push:
    branches:
      - main

jobs:
  rebase:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
         git config --global user.name "UjjwalAgr14"
         git config --global user.email "ujjwal@recruitcrm.io"
         git remote set-url origin https://github.com/UjjwalAgr14/rebase-automation-test.git
         git fetch origin dev
         git checkout dev
         git rebase origin/main
         git push origin HEAD:dev --force-with-lease
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
